import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * Export trip to a beautiful PDF
 * @param {Object} trip The trip object
 * @param {Object} options { template: 'modern' | 'classic' | 'family', includeImages: boolean }
 */
export const exportToBeautifulPDF = async (trip, options = { template: 'modern' }) => {
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;

    // Helper: Add text with auto-line break
    const addText = (text, x, y, size = 12, color = [0, 0, 0], font = 'helvetica', style = 'normal') => {
        doc.setFont(font, style);
        doc.setFontSize(size);
        doc.setTextColor(...color);
        return doc.text(text, x, y, { maxWidth: pageWidth - margin * 2 });
    };

    // --- HEADER ---
    // Background header color
    doc.setFillColor(63, 81, 181); // Indigo 500
    doc.rect(0, 0, pageWidth, 40, 'F');

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text(trip.name || "My Trip", margin, 20);

    // Date & Location
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    const dates = trip.startDate && trip.endDate
        ? `${new Date(trip.startDate).toLocaleDateString()} - ${new Date(trip.endDate).toLocaleDateString()}`
        : "Dates TBD";
    doc.text(`${dates} | ${trip.country || "Unknown Destination"}`, margin, 30);

    // --- CONTENT ---
    let y = 55;

    // Summary Section
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Trip Summary", margin, y);
    y += 10;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const summary = trip.notes || "No additional notes for this trip.";
    const splitSummary = doc.splitTextToSize(summary, pageWidth - margin * 2);
    doc.text(splitSummary, margin, y);
    y += splitSummary.length * 5 + 10;

    // Itinerary Section
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Itinerary", margin, y);
    y += 10;

    if (!trip.itinerary || trip.itinerary.length === 0) {
        doc.setFontSize(10);
        doc.setFont("helvetica", "italic");
        doc.text("No itinerary items yet.", margin, y);
    } else {
        // Group by Date
        const itemsByDate = trip.itinerary.reduce((acc, item) => {
            const date = item.date || 'Unscheduled';
            if (!acc[date]) acc[date] = [];
            acc[date].push(item);
            return acc;
        }, {});

        const sortedDates = Object.keys(itemsByDate).sort();

        sortedDates.forEach(date => {
            // Check page break
            if (y > pageHeight - 40) {
                doc.addPage();
                y = 20;
            }

            // Date Header
            doc.setFillColor(240, 240, 240);
            doc.rect(margin, y - 5, pageWidth - margin * 2, 8, 'F');
            doc.setFontSize(12);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(0, 0, 0);
            doc.text(date, margin + 2, y);
            y += 10;

            // Items
            itemsByDate[date].forEach((item, index) => {
                if (y > pageHeight - 30) {
                    doc.addPage();
                    y = 20;
                }

                const time = item.details?.time || "--:--";
                const location = item.details?.location || "No Location";
                const type = item.type?.toUpperCase() || "Activity";

                // Time bubble
                doc.setDrawColor(200, 200, 200);
                doc.setLineWidth(0.1);
                doc.circle(margin + 5, y - 1, 1.5, 'S'); // bullet point

                doc.setFontSize(10);
                doc.setFont("helvetica", "bold");
                doc.text(time, margin + 10, y);

                doc.setFont("helvetica", "normal");
                doc.text(`${location} (${type})`, margin + 30, y);

                y += 6;

                // Notes if any
                if (item.details?.notes) {
                    doc.setFontSize(8);
                    doc.setTextColor(100, 100, 100);
                    doc.text(item.details.notes, margin + 30, y);
                    doc.setTextColor(0, 0, 0);
                    y += 6;
                }

                y += 4; // Spacing between items
            });
            y += 5; // Spacing between days
        });
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${i} of ${pageCount} - Generated by Travel Together`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    }

    doc.save(`${trip.name || 'itinerary'}.pdf`);
};

export const exportToJSON = (trip) => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(trip, null, 2));
    const downloadAnchorNode = document.createElement('a');
    downloadAnchorNode.setAttribute("href", dataStr);
    downloadAnchorNode.setAttribute("download", `${trip.name || 'trip'}.json`);
    document.body.appendChild(downloadAnchorNode);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
};

/**
 * Export specific element to Image
 * @param {HTMLElement} element The DOM element to capture
 * @param {string} fileName The name of the file
 */
export const exportToImage = async (element, fileName) => {
    if (!element) return;
    try {
        const canvas = await html2canvas(element, {
            scale: 2, // Retina quality
            useCORS: true,
            backgroundColor: '#ffffff',
            logging: false
        });
        const link = document.createElement('a');
        link.download = `${fileName || 'trip-export'}.png`;
        link.href = canvas.toDataURL('image/png');
        link.click();
    } catch (err) {
        console.error("Export to image failed:", err);
        alert("匯出圖片失敗，請重試");
    }
};
